# Generated by Django 2.0.2 on 2018-03-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_project_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dp.Portfolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(),
        ),
    ]
