# Generated by Django 2.0.2 on 2018-03-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0003_auto_20180304_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('user_id', models.CharField(max_length=20)),
                ('pozice', models.CharField(max_length=200)),
            ],
        ),
    ]
