# Generated by Django 2.0.2 on 2018-03-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0005_auto_20180322_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dp.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dp.Portfolio'),
        ),
    ]
