# Generated by Django 2.0.2 on 2018-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0011_project_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.CharField(choices=[('0.25', 'Small'), ('0.50', 'Medium'), ('0.75', 'Large')], max_length=4),
        ),
    ]
