# Generated by Django 2.0.2 on 2018-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0013_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
    ]
