# Generated by Django 2.0.2 on 2018-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0015_auto_20180408_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='dp/static/photos/'),
        ),
    ]
