# Generated by Django 2.0.2 on 2018-04-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0018_project_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pozice',
            new_name='position',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
