# Generated by Django 2.0.2 on 2018-04-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0019_auto_20180408_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gender',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
    ]
