# Generated by Django 2.0.2 on 2018-04-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0021_ability_memberability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dp.Portfolio'),
        ),
    ]
