# Generated by Django 2.0.2 on 2018-04-15 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dp', '0022_auto_20180413_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.ProjectMember')),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(choices=[('1', 'Planned'), ('2', 'Ongoing'), ('3', 'Finished'), ('4', 'Interrupted')], max_length=1, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='popis',
            new_name='description',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='budget',
            field=models.DecimalField(decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='used_budget',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of deadline'),
        ),
        migrations.AddField(
            model_name='project',
            name='importance',
            field=models.CharField(choices=[('0.75', 'High '), ('0.50', 'Normal'), ('0.25', 'Low')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('1', 'Planned'), ('2', 'Ongoing'), ('3', 'Finished'), ('4', 'Interrupted'), ('5', 'Stopped')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='urgency',
            field=models.CharField(choices=[('0.75', 'High '), ('0.50', 'Normal'), ('0.25', 'Low')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='used_budget',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.CharField(choices=[('0.25', 'Small'), ('0.50', 'Medium'), ('0.75', 'Large')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='in_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Project'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Project'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Task'),
        ),
    ]
