# Generated by Django 2.0.2 on 2018-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0023_auto_20180415_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
    ]
