# Generated by Django 2.0.2 on 2018-04-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0024_auto_20180415_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Employee'),
        ),
    ]
