# Generated by Django 2.0.2 on 2018-04-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0025_auto_20180415_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Employee'),
        ),
    ]
