# Generated by Django 2.0.2 on 2018-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0027_auto_20180418_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedtask',
            old_name='assigned_to',
            new_name='employee',
        ),
    ]
