# Generated by Django 2.0.2 on 2018-04-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0031_auto_20180420_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
