# Generated by Django 2.0.2 on 2018-04-22 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0032_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of deadline'),
        ),
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pub_date',
            field=models.DateTimeField(editable=False, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
