# Generated by Django 2.0.2 on 2018-04-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0033_auto_20180422_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('project_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.ProjectMember')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('task_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.AssignedTask')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
