# Generated by Django 2.0.2 on 2018-04-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0034_auto_20180422_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnotes',
            name='project_author',
        ),
        migrations.RemoveField(
            model_name='tasknotes',
            name='task_author',
        ),
        migrations.AddField(
            model_name='projectnotes',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Employee'),
        ),
        migrations.AddField(
            model_name='projectnotes',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dp.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasknotes',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Employee'),
        ),
        migrations.AddField(
            model_name='tasknotes',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dp.Task'),
            preserve_default=False,
        ),
    ]
