# Generated by Django 2.0.2 on 2018-04-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0036_auto_20180430_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
