# Generated by Django 2.0.2 on 2018-05-02 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0038_auto_20180501_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('risk_appetite', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('risk_state', models.CharField(choices=[('0', 'Can happen'), ('1', 'Happening'), ('2', 'Resolved'), ('3', 'Wont happen')], max_length=1, null=True)),
                ('risk_has_impact_on', models.CharField(choices=[('0', 'project'), ('1', 'portfolio')], max_length=1, null=True)),
                ('risk_impact', models.CharField(choices=[('0.25', 'Small'), ('0.50', 'Medium'), ('0.75', 'Large')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'Planned'), ('2', 'Ongoing'), ('3', 'Finished'), ('4', 'Interrupted'), ('5', 'Stopped')], default=1, max_length=1)),
                ('progress', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'Planned'), ('2', 'Ongoing'), ('3', 'Finished'), ('4', 'Interrupted')], default=1, max_length=1)),
                ('progress', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='used_budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='project',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskstate',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dp.Task'),
        ),
        migrations.AddField(
            model_name='projectstate',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dp.Project'),
        ),
        migrations.AddField(
            model_name='projectrisk',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Project'),
        ),
        migrations.AddField(
            model_name='projectrisk',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Risk'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrisk',
            unique_together={('project', 'risk')},
        ),
    ]
