# Generated by Django 2.0.2 on 2018-05-03 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0039_auto_20180502_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='taskstate',
            name='task',
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('1', 'Planned'), ('2', 'Ongoing'), ('3', 'Finished'), ('4', 'Interrupted'), ('5', 'Stopped')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('1', 'Planned'), ('2', 'Ongoing'), ('3', 'Finished'), ('4', 'Interrupted')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='ProjectState',
        ),
        migrations.DeleteModel(
            name='TaskState',
        ),
    ]
