# Generated by Django 2.0.2 on 2018-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0045_auto_20180505_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrisk',
            name='probability',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Moderate'), ('3', 'High'), ('4', 'Very high')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='risk_impact',
            field=models.CharField(choices=[('1', 'Insignificant'), ('2', 'Minor'), ('3', 'Important'), ('4', 'Catastrophic')], max_length=1, null=True),
        ),
    ]
