# Generated by Django 2.0.2 on 2018-05-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0046_auto_20180505_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of start'),
        ),
    ]
