# Generated by Django 2.0.2 on 2018-05-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0047_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='date of deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of start'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='date of deadline'),
        ),
    ]
