# Generated by Django 2.0.2 on 2018-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0048_auto_20180506_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='possible_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
