# Generated by Django 2.0.2 on 2018-05-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0049_project_possible_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_word',
            field=models.CharField(choices=[('1', 'Government procurement'), ('2', 'Web analytics'), ('3', 'Optimization'), ('4', 'Consultation'), ('5', 'Security Software'), ('6', 'Information system'), ('7', 'R&D Project'), ('8', 'Machine learning')], max_length=1, null=True),
        ),
    ]
