# Generated by Django 2.0.2 on 2018-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0051_auto_20180508_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrisk',
            name='probability',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Very high')], null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='risk_has_impact_on',
            field=models.IntegerField(choices=[(0, 'project'), (1, 'portfolio')], null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='risk_impact',
            field=models.IntegerField(choices=[(1, 'Insignificant'), (2, 'Minor'), (3, 'Important'), (4, 'Catastrophic')], null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='risk_state',
            field=models.IntegerField(choices=[(0, 'Can happen'), (1, 'Happening'), (2, 'Resolved'), (3, 'Wont happen')], default=1),
        ),
    ]
