# Generated by Django 2.0.2 on 2018-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0052_auto_20180508_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key_word',
            field=models.IntegerField(choices=[('1', 'Government procurement'), ('2', 'Web analytics'), ('3', 'Optimization'), ('4', 'Consultation'), ('5', 'Security Software'), ('6', 'Information system'), ('7', 'R&D Project'), ('8', 'Machine learning')], null=True),
        ),
    ]
