# Generated by Django 2.0.2 on 2018-05-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0054_auto_20180509_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Strategy'),
        ),
        migrations.AddField(
            model_name='project',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dp.Strategy'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliostrategy',
            unique_together={('portfolio', 'strategy')},
        ),
    ]
