# Generated by Django 2.0.2 on 2018-05-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0057_organizationstrategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrisk',
            name='risk_has_impact_on',
        ),
    ]
