# Generated by Django 2.0.2 on 2018-05-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0060_remove_task_final_manhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
